@hostname = http://localhost:5020/api

### Menu Web Site
@urlS = Menu
GET {{hostname}}/{{urlS}}
Content-Type: application/json

### TypeProduct
@urlT = TypeProduct
GET {{hostname}}/{{urlT}}
Content-Type: application/json

### Lista de Usuarios
@urlU = Usuario
GET {{hostname}}/{{urlU}}
Content-Type: application/json

### Usuario Register
@register = register
POST {{hostname}}/{{urlU}}/{{register}}
Content-Type: application/json

 {
    "username": "Julian",
    "email": "julina@gmail.com",
    "password": "index"
 }

### Usuario Login
@login = token
POSt {{hostname}}/{{urlU}}/{{login}}
Content-Type: application/json

{
  "email": "chris@gmail.com",
  "password" : "index"
}