@hostname = http://localhost:5020/api
### Category
@urlC = Category
GET {{hostname}}/{{urlC}}
Content-Type: application/json

### SubCategory
@urlS = SubCategory
GET {{hostname}}/{{urlS}}
Content-Type: application/json

### TypeProduct
@urlT = TypeProduct
GET {{hostname}}/{{urlT}}
Content-Type: application/json

### TypeProduct
@urlP = Product
GET {{hostname}}/{{urlP}}
Content-Type: application/json

### Usuarios GET
@urlU = Usuario
GET {{hostname}}/{{urlU}}
Content-Type: application/json

### Usuario Register POST
@register = register
POST {{hostname}}/{{urlU}}/{{register}}
Content-Type: application/json

 {
    "username": "aa",
    "email": "chrisaaaaaaaasdf@gmail.com",
    "password": ""
 }

### Usuario Login POST
@login = token
POSt {{hostname}}/{{urlU}}/{{login}}
Content-Type: application/json

{
  "email": "chris@gmail.com",
  "password" : "index"
}

### Home 
